### ISSUE TITLE
What about AtlantaRUsers github organization?

### ISSUE THREAD

**Issue by bbrewington** [mattmills49/AtlantaRUsers#1]
Looks like this repo is a duplicate with www.github.com/atlantarusers - I prefer that one since it's easier to remember for people than mattmills49/atlantarusers no offense :)

Do you have access to that repo?

**Comment by mdtdev** [comment]
I can't tell -- is that a user account or an organization? 

If you want it, https://github.com/Atlanta-R-Meetup is mine and I can add anyone to it as admin.

**Comment by bbrewington** [comment]
Pretty sure the atlantaRusers one is a user account.

Yeah, if you wouldn't mind adding me, as well as @mattmills49 if he ok's using the Atlanta-R-Meetup one for the group

**Comment by mdtdev** [comment]
Ok, I went ahead and added both of you as owners of the organization. I think the gives you all the permissions you could want, if not let me know. I am not so great with permissions on Github yet.

**Comment by bbrewington** [comment]
Ok thanks, sounds good.  Closing this issue

**Comment by mattmills49** [comment]
Hey guys, thanks for bringing this up and I just want to apologize for not getting back to y'all. One of my goals is to standardize the naming conventions we use so I'm gonna take the weekend and think about all that just to be sure we don't have to do redo this if we think of something better down the road. I'll have an answer for y'all by the start of next week.

**Comment by mdtdev** [comment]
When you say naming conventions, do you mean overall for the group/github or for the organization of the talks? For the latter, we should probably name or index by date **and** topic, so people can look stuff up way after the fact without having to load each date's folder to see them. We could update a readme at the root with date/topics and direct link the directories from there.

If you are talking about other stuff, I'd be curious to know what you mean. Cheers!

**Comment by chrisspruck** [comment]
> When you say naming conventions, do you mean overall for the group/github or for the organization of the talks? For the latter, we should probably name or index by date and topic

Hello! I've been following the group a while (though haven't been able to attend yet) and am excited about Matt's reboot. Just a suggestion on the naming convention - format things so they're date-sortable, e.g.

2018-04-17-h20.ai-and-RShiny
2018-05-15-next-months-topic
2018-05-29-hack-night-files
and so on.

**Comment by dermcnor** [comment]
Sorry, this thread went to spam for me.  That is the organization I made
for the group before.  I am happy to add you if you like or use the new
one.  Up to you.

**Comment by dermcnor** [comment]
Hit send too early... Here was the original github

https://github.com/ATL-RUG

**Comment by mattmills49** [comment]
Thanks for the thoughts guys and sorry for the delay in getting to this. I'm going to move this repo to the atlantaRUsers repo; it has the same naming convention of the twitter account I made and is closer to the Meetup name (but opposite of the url, ugh haha). Thanks for the comments.
